name: DevOpsHacka03 Web Pipeline

on: 
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        env:
          REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate Build
        run: |
          npm ci
          npm run build

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Autenticação no Google Cloud
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Deploy Frontend no Cloud Run
        id: deploy
        run: |-
          gcloud run deploy frontend \
            --quiet \
            --region  ${{ secrets.GOOGLE_REGION }} \
            --image ${{ secrets.ARTIFACT_REGISTRY }}/frontend:latest \
            --platform managed \
            --set-env-vars REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }} \
            --allow-unauthenticated \
            --project ${{ secrets.GOOGLE_PROJECT_ID }} \
            --format json