name: DevOpsHacka03 Web Pipeline

on: 
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        env:
          REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate Build
        run: |
          npm ci
          npm run build